### ISSUE TITLE
Only one doubt

### ISSUE THREAD

**Issue by aliggie** [MacWarrior/clipbucket-v5#123]
Hi,
I love ClipBucket and recently I started making some improvements. I had noticed it had been stuck for over a year, but I was hoping it would wake up ... I could collaborate in this repository, but if the official repository wakes up, what do we do?

Another question: I made some changes, how do you merge the changes to this repository?
Do I keep making changes to the official repository or is it better to fork this?

Thanks

**Comment by MacWarrior** [comment]
Hi, 

Thanks for coming !

For the past year, CB has been closing issues without any commit or fix and it can only mean 2 things in my opinion : 
- They abandonned CB for other projects
- They now only work on private repo (aka. closed source)

As long as they pushed something, I merged and will continue to merge their commits to this repo.

As you can see, I've made a huge amount of modifications on this repo, and even if my roadmap isn't public (for now, who knows...), I have plans for lots of improvements.
The merge request you made on official repo isn't compatible with my repo (Maybe 80-90% compatible because you mainly edited files I didn't touch so much) ; I don't thik it's possible to merge your pull request from another repo ; you can adapt them on a new fork or I can also do it (and of course add a copyright to you in the commit message)

The simpliest and most effiscient way to work together is for you to create a new fork to work on ; and if you do so, I'll be glad to hear from you after your migration (Which has to be manual for now : a sql fle to apply ; but a refactoring of the upgrade system is on my todo list !)

Don't hesitate to ask me any question

**Comment by spirogg** [comment]
@aliggie @MacWarrior this would be great. I am greatful for all the changes. Hopefully @aliggie you can fork this repo and continue to improve with @MacWarrior  you guys are the best I'm not a programmer but can test and report bugs as before again. Hope you both are well and family safe

**Comment by aliggie** [comment]
Thanks for the thought. All right, fortunately.
I have finished applying all my updates from the official repository and will continue here. 
I am happy that ClipBucket shines!

**Comment by MacWarrior** [comment]
Hi @spirogg 
Thanks for your messages ; hope everything is ok from your side too !

I'm glad we're all going to work together building a better ClipBucket than never before 😉
