### ISSUE TITLE
Blank page for PHP 7.3 and 7.4

### ISSUE THREAD

**Issue by KamillaPup** [MacWarrior/clipbucket-v5#162]
I keep getting this error on my Ubuntu Plesk server:

`AH01071: Got error 'PHP message: PHP Fatal error:  Cannot redeclare error() in /var/www/vhosts/raisedtails.org/httpdocs/includes/functions.php on line 1420'`

When I switch to 7.0 it works. I had this same issue with ClipBucket v4.2RC and had to stay downgraded at 7.0.

**Comment by MacWarrior** [comment]
Hello @KamillaPup,

It's strange because I use php 7.3 and don't have this kind of error
Do you use the last revision or the last release ? In case of last release, can you try last revision ?

I know there is currently some PHP 7.4.X incompatibility and I'll work on it asap

Best regards,
MacWarrior.

**Comment by KamillaPup** [comment]
I'm sorry I ended up moving to AVideo so I can't troubleshoot it anymore.
