### ISSUE TITLE
Can`t upload video

### ISSUE THREAD

**Issue by grechxn** [MacWarrior/clipbucket-v5#242]
I downloaded Clipbucket v5, everything work fine, except interface, but it doesnt matter much. The main problem, is that i cant upload any video, not by drag and drop, either not with "grab from youtube". The function grab from youtube isnt working, i`ve already have read about it, but nobody was  writing about drag and drop function, so i really need help. Maybe the reason is exactly in interface? Like css or javascript arent available, idk.
![image](https://user-images.githubusercontent.com/105740710/168875394-b557dfc5-d9e8-46d6-958a-f0abfef0ec85.png)

**Comment by grechxn** [comment]
> I downloaded Clipbucket v5, everything work fine, except interface, but it doesnt matter much.

**Comment by MacWarrior** [comment]
Hello @grechxn, 

It looks like you have some hosting issues and I bet this is because you use a subdirectory for clipbucket, but unfortunately CB doesn't support to be stored in a subdirectory
Can you try moving all sources to parent directory so they can be accessed without subdir ?

This precise subject is in my todo but require lot of work...

Best regards,
MacWarrior.
