### ISSUE TITLE
I can't create Russian language pack. And similar pages shown 500 error.

### ISSUE THREAD

**Issue by 3aPa3a-Bratsk** [MacWarrior/clipbucket-v5#258]
![Снимок экрана 2023-04-11 220813](https://user-images.githubusercontent.com/71819314/231189988-787cb445-d73e-4dce-a6ab-df789c2251e4.png)
Sorry for my english.. I'm from Russia ))

**Comment by 3aPa3a-Bratsk** [comment]
![Снимок экрана 2023-04-11 221708](https://user-images.githubusercontent.com/71819314/231191853-4216338c-406f-46c3-bb39-3e1d2104f21e.png)

**Comment by 3aPa3a-Bratsk** [comment]
![Снимок экрана 2023-04-11 221839](https://user-images.githubusercontent.com/71819314/231192274-155a6e57-ebd1-4f22-a18d-a57ca521fcfc.png)

**Comment by MacWarrior** [comment]
Hello @3aPa3a-Bratsk, 

Thanks for report ; language generation is sadly broken since original version and I didn't rewrite it yet...
To add a new language, you have to do it manually by copying en.lang to rus.lang
Then add an entry in {db_prefix}_languages (also check #253 )

If you want, share your .lang file and I'll add it to the repository

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hi @3aPa3a-Bratsk,

Some plugins also haven't been rewritten and simply don't work ; which plugin did you tried to enable ?

Best regards,
MacWarrior.

**Comment by 3aPa3a-Bratsk** [comment]
![Снимок экрана 2023-04-11 222849](https://user-images.githubusercontent.com/71819314/231195337-72c9bc56-2285-4789-a4f5-e1bc4a3059a3.png)

**Comment by MacWarrior** [comment]
Both are not rewritten and so won't work
