### ISSUE TITLE
Software architecture is challanging 

### ISSUE THREAD

**Issue by orlovskyjavaprofi** [MacWarrior/clipbucket-v5#272]
So this project i must admit , have the most complex software architecture, those functions.php acting almost like a god object, 
and figuring out how the data instantiated is very hard, i really amazed how you devs of clipbucket-v5 did pull it out.
What to improve , i just that movement towards batter js libraries and more clean code is possible, we need to use chatgpt a lot to streamlined the code.
**I use dev version of clipbucket ,**  i already commit some code changes (Thanks to chatgpt), but there a lot of unstable code **don't expect that i will do it on constant base.**

**Comment by MacWarrior** [comment]
Hello @orlovskyjavaprofi, 

ClipbucketV5 is a fork or original Clipbucket created more than 8 years ago ; since then, we haven't stop increasing functionnal and code quality step by step.
You can make sure we clearly and daily see how code quality is because we also have to deal with it, but this don't prevent us to improve things, fix issues and add new functionnalities to make it way better every day

Dev version has way more fixes and new features ; it will be realeased soon, as HLS video conversion is almost finished.
Don't hesitate to make merge request, we'll study them.

Best regards,
MacWarrior.
